### ISSUE TITLE
cgi released with Ruby 3.0.2 does not match released gem

### ISSUE THREAD

**Issue by headius** [ruby/cgi#10]
The release of Ruby 3.0.2 shipped changes to the CGI library, including (but not limited to) #4, changes that came from a JRuby contributor. However, Ruby 3.0.2 claims to be shipping the 0.2.0 released gem.

The gem needs to be updated and released.

JRuby only sources gem-based standard libraries from released gems, and when the released gem does not match what the Ruby version claims, we **have no way to install the correct library**.

**Comment by headius** [comment]
Note this will be largely defunct if we get a release out with JRuby support in #9.

**Comment by hsbt** [comment]
@headius Is there still issues for this? I'd support this.

**Comment by hsbt** [comment]
Ruby 3.0 is only security maintenance phase. I'll close this because we can't fix inconsistent files.
